################################################################
# Manage the virtual environment
A   = . ../../venv/bin/activate
PY=python3.12
PYTHON=$(A) ; $(PY)

pytest-debug:
	$(PYTHON) -m pytest -v --log-cli-level=DEBUG .
